"""add User, Teacher and Report table

Revision ID: 3bff10ba2e2a
Revises: 
Create Date: 2019-12-16 21:22:34.269193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bff10ba2e2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_name', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_teacher_id', sa.Integer(), nullable=True),
    sa.Column('assistant_teacher_id', sa.Integer(), nullable=True),
    sa.Column('teaching_date', sa.Date(), nullable=True),
    sa.Column('submit_date', sa.DateTime(), nullable=True),
    sa.Column('teaching_content', sa.String(length=200), nullable=True),
    sa.Column('student_attendance', sa.Integer(), nullable=True),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assistant_teacher_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['main_teacher_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_teaching_date'), 'reports', ['teaching_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_teaching_date'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('users')
    op.drop_table('teachers')
    # ### end Alembic commands ###
